n5: prevent failure on missing group metadata
In the N5 spec, https://github.com/saalfeldlab/n5#file-system-specification
point 3, the `{"n5": "$version"}` metadata is only expected at the root level.
Datasets missing the metadata on inner groups fail to load:

```
In [43]: list(zarr.hierarchy.Group(store=zarr.n5.N5Store("ex.n5")).groups())
...
ValueError: group not found at path 'setup0'
```

This changes the group parsing logic to not fail if the metadata is
missing. Suggestions welcome on how to detect the top group/array in
order to special case the parsing.